In [1]:
import os
os.chdir('..')
%pwd

'f:\\End_To_End_project\\Ham_Spam_Classifier(ETE)'

In [71]:
import pandas as pd

path = r"artifact\01_25_2024_15_11_32\data_validation\invalid\invalidated_data.csv"
df = pd.read_csv(path)

In [72]:
df.shape

(5572, 2)

In [73]:
from src.utils import *
from src.models.label_encoding import LabelConverter

In [74]:
label_converter = LabelConverter()
df["Target"] = df["Target"].apply(lambda x: label_converter.ham if x == 'ham' else label_converter.spam)
df.head()

Target                                       Text_Message
0       0  Go until jurong point, crazy.. Available only ...
1       0                      Ok lar... Joking wif u oni...
2       1  Free entry in 2 a wkly comp to win FA Cup fina...
3       0  U dun say so early hor... U c already then say...
4       0  Nah I don't think he goes to usf, he lives aro...

In [75]:
spam = df[df.Target ==1]
ham = df[df.Target ==0]

In [76]:
spam

Target                                       Text_Message
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
5          1  FreeMsg Hey there darling it's been 3 week's n...
8          1  WINNER!! As a valued network customer you have...
9          1  Had your mobile 11 months or more? U R entitle...
11         1  SIX chances to win CASH! From 100 to 20,000 po...
...      ...                                                ...
5537       1  Want explicit SEX in 30 secs? Ring 02073162414...
5540       1  ASKED 3MOBILE IF 0870 CHATLINES INCLU IN FREE ...
5547       1  Had your contract mobile 11 Mnths? Latest Moto...
5566       1  REMINDER FROM O2: To get 2.50 pounds free call...
5567       1  This is the 2nd time we have tried 2 contact u...

[747 rows x 2 columns]

In [8]:
ham

Target                                       Text_Message
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
6          0  Even my brother is not like to speak with me. ...
...      ...                                                ...
5565       0                                       Huh y lei...
5568       0              Will Ì_ b going to esplanade fr home?
5569       0  Pity, * was in mood for that. So...any other s...
5570       0  The guy did some bitching but I acted like i'd...
5571       0                         Rofl. Its true to its name

[4825 rows x 2 columns]

In [9]:
spam.Text_Message.values[0]

"Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's"

In [10]:
data_cleaning(spam.Text_Message.values[0])

"free entri 2 week comp win fa cup final tkts 21st may 2005. text fa 87121 receiv entri question ( std txt rate ) & c 's appli 08452810075over18 's"

In [11]:
df["clean_data"] = [data_cleaning(i) for i in df.Text_Message.values]

In [12]:
df

Target                                       Text_Message  \
0          0  Go until jurong point, crazy.. Available only ...   
1          0                      Ok lar... Joking wif u oni...   
2          1  Free entry in 2 a wkly comp to win FA Cup fina...   
3          0  U dun say so early hor... U c already then say...   
4          0  Nah I don't think he goes to usf, he lives aro...   
...      ...                                                ...   
5567       1  This is the 2nd time we have tried 2 contact u...   
5568       0              Will Ì_ b going to esplanade fr home?   
5569       0  Pity, * was in mood for that. So...any other s...   
5570       0  The guy did some bitching but I acted like i'd...   
5571       0                         Rofl. Its true to its name   

                                             clean_data  
0     go jurong point , crazi .. avail bugi n great ...  
1                               ok lar ... joke oni ...  
2     free entri 2 week comp win fa cup final tkts 2...  
3               dun say earli hor ... c alreadi say ...  
4            nah n't think goe usf , live around though  
...                                                 ...  
5567  2nd time tri 2 contact . å£750 pound prize . 2...  
5568                         ì_ b go esplanad fr home ?  
5569                      piti , * mood . ... suggest ?  
5570  guy bitch act like 'd interest buy someth els ...  
5571                       roll floor laugh . true name  

[5572 rows x 3 columns]

In [13]:
from nltk.tokenize import word_tokenize

df['tokenized_data'] = df['clean_data'].apply(word_tokenize)
df['word_length'] = [len(i) for i in df['tokenized_data']]

In [14]:
df

Target                                       Text_Message  \
0          0  Go until jurong point, crazy.. Available only ...   
1          0                      Ok lar... Joking wif u oni...   
2          1  Free entry in 2 a wkly comp to win FA Cup fina...   
3          0  U dun say so early hor... U c already then say...   
4          0  Nah I don't think he goes to usf, he lives aro...   
...      ...                                                ...   
5567       1  This is the 2nd time we have tried 2 contact u...   
5568       0              Will Ì_ b going to esplanade fr home?   
5569       0  Pity, * was in mood for that. So...any other s...   
5570       0  The guy did some bitching but I acted like i'd...   
5571       0                         Rofl. Its true to its name   

                                             clean_data  \
0     go jurong point , crazi .. avail bugi n great ...   
1                               ok lar ... joke oni ...   
2     free entri 2 week comp win fa cup final tkts 2...   
3               dun say earli hor ... c alreadi say ...   
4            nah n't think goe usf , live around though   
...                                                 ...   
5567  2nd time tri 2 contact . å£750 pound prize . 2...   
5568                         ì_ b go esplanad fr home ?   
5569                      piti , * mood . ... suggest ?   
5570  guy bitch act like 'd interest buy someth els ...   
5571                       roll floor laugh . true name   

                                         tokenized_data  word_length  
0     [go, jurong, point, ,, crazi, .., avail, bugi,...           20  
1                        [ok, lar, ..., joke, oni, ...]            6  
2     [free, entri, 2, week, comp, win, fa, cup, fin...           30  
3     [dun, say, earli, hor, ..., c, alreadi, say, ...]            9  
4     [nah, n't, think, goe, usf, ,, live, around, t...            9  
...                                                 ...          ...  
5567  [2nd, time, tri, 2, contact, ., å£750, pound, ...           24  
5568                 [ì_, b, go, esplanad, fr, home, ?]            7  
5569             [piti, ,, *, mood, ., ..., suggest, ?]            8  
5570  [guy, bitch, act, like, 'd, interest, buy, som...           14  
5571                [roll, floor, laugh, ., true, name]            6  

[5572 rows x 5 columns]

In [15]:
sorted_df = df.sort_values(by='word_length', ascending=True)


In [16]:
sorted_df.tokenized_data


5268                                                [\er]
5188                                                [oki]
3049                                                 [ok]
1924                                                 [ok]
3092    [staff.science.nus.edu.sg/~phyhcmk/teaching/pc...
                              ...                        
1862    [last, thing, ever, want, hurt, ., n't, think,...
2157    [sad, stori, man, -, last, week, b'day, ., wif...
2847    [sad, stori, man, -, last, week, b'day, ., wif...
2433    [indian, poor, india, poor, countri, ., say, o...
1578    [make, girl, happi, ?, 's, difficult, make, gi...
Name: tokenized_data, Length: 5572, dtype: object

In [17]:
", ".join(map(str, sorted_df['word_length'].values))

'1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 

In [18]:
sorted_df.tokenized_data

5268                                                [\er]
5188                                                [oki]
3049                                                 [ok]
1924                                                 [ok]
3092    [staff.science.nus.edu.sg/~phyhcmk/teaching/pc...
                              ...                        
1862    [last, thing, ever, want, hurt, ., n't, think,...
2157    [sad, stori, man, -, last, week, b'day, ., wif...
2847    [sad, stori, man, -, last, week, b'day, ., wif...
2433    [indian, poor, india, poor, countri, ., say, o...
1578    [make, girl, happi, ?, 's, difficult, make, gi...
Name: tokenized_data, Length: 5572, dtype: object

In [19]:
words = [words for lists in sorted_df.tokenized_data for words in lists]
words

['\\er',
 'oki',
 'ok',
 'ok',
 'staff.science.nus.edu.sg/~phyhcmk/teaching/pc1323',
 'yup',
 'oki',
 '@',
 'ok',
 '...',
 'phone',
 '6time',
 'hungri',
 'yup',
 'food',
 'respond',
 'alrit',
 '...',
 'idea',
 'g.w.are',
 'ok',
 '645',
 'oki',
 'oki',
 'pock',
 'like',
 '?',
 'number',
 'sir',
 '.',
 'happen',
 'ok',
 '...',
 'buy',
 '.',
 'brother',
 'genius',
 'talk',
 '..',
 'plan',
 '?',
 'late',
 '.',
 '\\hey',
 'kate',
 'movi',
 'laptop',
 'look',
 '?',
 'ok',
 '.',
 'come',
 'home',
 'ok',
 '...',
 'today',
 '?',
 'nite',
 '...',
 'know',
 'call',
 'good',
 'hear',
 ':',
 ')',
 'wana',
 'see',
 'ever',
 'easier',
 'happi',
 'say',
 'see',
 '!',
 'meet',
 '?',
 'sis',
 '?',
 'never',
 'noth',
 'convey',
 'regard',
 'anyth',
 '...',
 'way',
 'home',
 'b4',
 'thursday',
 'unbeliev',
 'faglord',
 '2',
 '.',
 'drop',
 'tank',
 'eye',
 'philosophi',
 'wat',
 '?',
 'lectur',
 '?',
 'yeah',
 'wors',
 'much',
 'buzi',
 'ok',
 '...',
 'much',
 'buzi',
 'k.',
 'sent',
 'bluray',
 'player',

In [20]:
print(len(words),len(set(words)))

68098 7993


In [21]:
sorted_df['word_length'].value_counts()

word_length
5      481
6      432
4      395
7      387
8      364
      ... 
61       1
58       1
43       1
49       1
202      1
Name: count, Length: 66, dtype: int64

In [22]:
df.isna().sum()

Target            0
Text_Message      0
clean_data        0
tokenized_data    0
word_length       0
dtype: int64

In [23]:
# from collections import Counter
# def frequency_count(df):
#     word = []
#     for text in df:
#         sentenc = text.split()
#         for i in sentenc:
#             word.append(i)
#     freq = Counter(word)
#     word_freq = pd.DataFrame(freq.items(),columns=['word','frequency'])
#     sf = word_freq.sort_values(by='frequency')
#     return sf

In [24]:
import nltk
from nltk.tokenize import word_tokenize

def frequency_count(df):
    word_list = []

    for text in df:
        tokens = word_tokenize(text)
        word_list.extend(tokens)

    freq = Counter(word_list)
    word_freq = pd.DataFrame(freq.items(), columns=['word', 'frequency'])
    sf = word_freq.sort_values(by='frequency', ascending=False)

    return sf

In [25]:
sf = frequency_count(df.clean_data)

In [26]:
os.makedirs("frequency_count",exist_ok= True)
save_data(sf, os.path.join("frequency_count","data.csv"))

NameError: name 'save_data' is not defined

In [ ]:
sf.head(10)

word  frequency
84      .       4769
3       ,       1872
74      ?       1541
69      !       1381
14    ...       1131
45      &        916
283     ;        764
169     :        717
5      ..        681
114  call        656

In [27]:
new_df = df[['Target','clean_data']]

In [28]:
new_df 

Target                                         clean_data
0          0  go jurong point , crazi .. avail bugi n great ...
1          0                            ok lar ... joke oni ...
2          1  free entri 2 week comp win fa cup final tkts 2...
3          0            dun say earli hor ... c alreadi say ...
4          0         nah n't think goe usf , live around though
...      ...                                                ...
5567       1  2nd time tri 2 contact . å£750 pound prize . 2...
5568       0                         ì_ b go esplanad fr home ?
5569       0                      piti , * mood . ... suggest ?
5570       0  guy bitch act like 'd interest buy someth els ...
5571       0                       roll floor laugh . true name

[5572 rows x 2 columns]

In [29]:
import pandas as pd
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense



In [30]:
max_words = 6000  
max_len = 60 

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(df['clean_data'])

In [31]:
tokenizer.word_counts

OrderedDict([('go', 453),
             ('jurong', 1),
             ('point', 33),
             ('crazi', 14),
             ('avail', 17),
             ('bugi', 7),
             ('n', 152),
             ('great', 117),
             ('world', 40),
             ('la', 7),
             ('e', 96),
             ('buffet', 2),
             ('cine', 7),
             ('got', 251),
             ('amor', 1),
             ('wat', 113),
             ('ok', 292),
             ('lar', 38),
             ('joke', 16),
             ('oni', 4),
             ('free', 282),
             ('entri', 26),
             ('2', 515),
             ('week', 179),
             ('comp', 12),
             ('win', 83),
             ('fa', 4),
             ('cup', 8),
             ('final', 33),
             ('tkts', 4),
             ('21st', 3),
             ('may', 50),
             ('2005', 3),
             ('text', 230),
             ('87121', 4),
             ('receiv', 46),
             ('question', 37),
          

In [32]:

tokenizer.index_docs

defaultdict(int,
            {570: 17,
             666: 13,
             1151: 7,
             3767: 1,
             309: 33,
             89: 85,
             77: 108,
             3768: 1,
             1150: 7,
             2577: 2,
             256: 37,
             4: 419,
             70: 109,
             20: 239,
             1149: 7,
             43: 124,
             594: 16,
             1675: 4,
             270: 37,
             13: 279,
             2016: 3,
             276: 37,
             304: 34,
             30: 154,
             765: 12,
             31: 165,
             2578: 2,
             1042: 8,
             2015: 3,
             222: 42,
             111: 77,
             1676: 2,
             15: 227,
             1677: 4,
             68: 112,
             1678: 4,
             397: 21,
             812: 11,
             24: 208,
             310: 33,
             2: 412,
             311: 33,
             3: 440,
             207: 48,
             97: 89

In [33]:
sequences = tokenizer.texts_to_sequences(df['clean_data'])
sequences

[[4,
  3767,
  309,
  666,
  570,
  1149,
  43,
  70,
  256,
  1150,
  89,
  2577,
  1151,
  20,
  3768,
  77],
 [13, 270, 594, 1675],
 [15,
  397,
  2,
  30,
  765,
  111,
  1676,
  1042,
  310,
  1677,
  2015,
  207,
  2016,
  24,
  1676,
  1678,
  222,
  397,
  276,
  812,
  31,
  304,
  68,
  3,
  311,
  2578,
  3],
 [185, 50, 312, 2579, 68, 97, 50],
 [872, 8, 35, 398, 813, 179, 161, 382],
 [667,
  79,
  1152,
  3,
  103,
  30,
  3,
  172,
  41,
  383,
  17,
  324,
  39,
  1679,
  13,
  313,
  812,
  3769,
  25,
  260,
  173,
  2580],
 [96, 492, 17, 293, 515, 17, 2581, 3770],
 [176,
  814,
  1300,
  1300,
  1680,
  2017,
  2018,
  2019,
  233,
  399,
  873,
  540,
  709,
  338,
  815,
  84,
  873],
 [595,
  571,
  294,
  156,
  285,
  2582,
  1153,
  90,
  710,
  72,
  1,
  2583,
  72,
  339,
  2584,
  422,
  816,
  201],
 [42, 572, 197, 1043, 410, 257, 400, 42, 271, 15, 1, 42, 410, 181, 15, 2585],
 [7, 174, 82, 34, 134, 8, 23, 146, 223, 1044, 162, 45, 98, 1154, 358, 29],
 [1681,
 

In [34]:
len(sequences)

5572

In [35]:
padded_sequences = pad_sequences(sequences, maxlen=60,truncating='post',padding="post")
padded_sequences

array([[   4, 3767,  309, ...,    0,    0,    0],
       [  13,  270,  594, ...,    0,    0,    0],
       [  15,  397,    2, ...,    0,    0,    0],
       ...,
       [1146, 1493,    0, ...,    0,    0,    0],
       [ 160, 1413, 1833, ...,    0,    0,    0],
       [1886, 1323,   91, ...,    0,    0,    0]])

In [36]:
len(padded_sequences)

5572

In [38]:
padded_sequences[0:10]

array([[   4, 3767,  309,  666,  570, 1149,   43,   70,  256, 1150,   89,
        2577, 1151,   20, 3768,   77,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [  13,  270,  594, 1675,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0],
       [  15,  397,    2,   30,  765,  111, 1676, 1042,  310, 1677, 2015,
         207, 2016,   24, 1676, 1678,  222,  397,  276,  812,   31,  304,
          68,    3,  311, 2578,   

In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, SimpleRNN, Dense
from sklearn.preprocessing import LabelEncoder


In [2]:

data = {'Target': [0,0, 1, 0, 1],
        'clean_data': ["0 1 ok",'go jurong point, crazy ok', ' ok free entry week comp', 'ok dun say early', 'ok nah think goes usf']}

df = pd.DataFrame(data)
df

Target                 clean_data
0       0                     0 1 ok
1       0  go jurong point, crazy ok
2       1    ok free entry week comp
3       0           ok dun say early
4       1      ok nah think goes usf

In [3]:
from nltk.tokenize import word_tokenize
print([word_tokenize(sen) for sen in df['clean_data'] ])
print([(sen.split(' ')) for sen in df['clean_data'] ])

[['0', '1', 'ok'], ['go', 'jurong', 'point', ',', 'crazy', 'ok'], ['ok', 'free', 'entry', 'week', 'comp'], ['ok', 'dun', 'say', 'early'], ['ok', 'nah', 'think', 'goes', 'usf']]
[['0', '1', 'ok'], ['go', 'jurong', 'point,', 'crazy', 'ok'], ['', 'ok', 'free', 'entry', 'week', 'comp'], ['ok', 'dun', 'say', 'early'], ['ok', 'nah', 'think', 'goes', 'usf']]


In [4]:
df['word_count'] = [len(sen.split(' ')) for sen in df['clean_data'] ]
df

Target                 clean_data  word_count
0       0                     0 1 ok           3
1       0  go jurong point, crazy ok           5
2       1    ok free entry week comp           6
3       0           ok dun say early           4
4       1      ok nah think goes usf           5

In [5]:
all_words = [word for sen in df['clean_data'] for word in sen.split()]
len(all_words),len(set(all_words))

(22, 18)

In [7]:
max_words = 16 
max_len = 3

In [8]:
tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(df['clean_data'])

In [9]:
tokenizer.index_word

{1: 'ok',
 2: '0',
 3: '1',
 4: 'go',
 5: 'jurong',
 6: 'point',
 7: 'crazy',
 8: 'free',
 9: 'entry',
 10: 'week',
 11: 'comp',
 12: 'dun',
 13: 'say',
 14: 'early',
 15: 'nah',
 16: 'think',
 17: 'goes',
 18: 'usf'}

In [10]:
tokenizer.index_docs

defaultdict(int,
            {2: 1,
             1: 5,
             3: 1,
             7: 1,
             6: 1,
             4: 1,
             5: 1,
             9: 1,
             8: 1,
             10: 1,
             11: 1,
             14: 1,
             13: 1,
             12: 1,
             15: 1,
             18: 1,
             17: 1,
             16: 1})

In [11]:
tokenizer.word_counts

OrderedDict([('0', 1),
             ('1', 1),
             ('ok', 5),
             ('go', 1),
             ('jurong', 1),
             ('point', 1),
             ('crazy', 1),
             ('free', 1),
             ('entry', 1),
             ('week', 1),
             ('comp', 1),
             ('dun', 1),
             ('say', 1),
             ('early', 1),
             ('nah', 1),
             ('think', 1),
             ('goes', 1),
             ('usf', 1)])

In [12]:
tokenizer.word_index

{'ok': 1,
 '0': 2,
 '1': 3,
 'go': 4,
 'jurong': 5,
 'point': 6,
 'crazy': 7,
 'free': 8,
 'entry': 9,
 'week': 10,
 'comp': 11,
 'dun': 12,
 'say': 13,
 'early': 14,
 'nah': 15,
 'think': 16,
 'goes': 17,
 'usf': 18}

In [13]:
sequences = tokenizer.texts_to_sequences(df['clean_data'])
sequences

[[2, 3, 1], [4, 5, 6, 7, 1], [1, 8, 9, 10, 11], [1, 12, 13, 14], [1, 15]]

In [14]:
padded_sequences = pad_sequences(sequences, maxlen=10,truncating='post',padding="post")
padded_sequences

array([[ 2,  3,  1,  0,  0,  0,  0,  0,  0,  0],
       [ 4,  5,  6,  7,  1,  0,  0,  0,  0,  0],
       [ 1,  8,  9, 10, 11,  0,  0,  0,  0,  0],
       [ 1, 12, 13, 14,  0,  0,  0,  0,  0,  0],
       [ 1, 15,  0,  0,  0,  0,  0,  0,  0,  0]])

In [15]:
df

Target                 clean_data  word_count
0       0                     0 1 ok           3
1       0  go jurong point, crazy ok           5
2       1    ok free entry week comp           6
3       0           ok dun say early           4
4       1      ok nah think goes usf           5

In [ ]:

# Tokenization and padding
max_words = 20  # Adjust based on your vocabulary size
max_len = 5  # Adjust based on your sequence length

tokenizer = Tokenizer(num_words=max_words)
tokenizer.fit_on_texts(df['clean_data'])
sequences = tokenizer.texts_to_sequences(df['clean_data'])
padded_sequences = pad_sequences(sequences, maxlen=max_len)

# Encoding target variable
label_encoder = LabelEncoder()
df['Target'] = label_encoder.fit_transform(df['Target'])

In [16]:
import pickle

with open('tokenizer1.pkl', 'wb') as tokenizer_file:
    pickle.dump(tokenizer, tokenizer_file)
with open('tokenizer1.pkl', 'rb') as tokenizer_file:
    loaded_tokenizer = pickle.load(tokenizer_file)

In [17]:
with open('tokenizer1.pkl', 'rb') as tokenizer_file:
    loaded_tokenizer = pickle.load(tokenizer_file)

In [21]:
new_text = ["	go jurong point, crazy ok"]
new_sequences = loaded_tokenizer.texts_to_sequences(new_text)
new_sequences


[[4, 5, 6, 7, 1]]

In [41]:
df

Target                                       Text_Message
0       ham  Go until jurong point, crazy.. Available only ...
1       ham                      Ok lar... Joking wif u oni...
2      spam  Free entry in 2 a wkly comp to win FA Cup fina...
3       ham  U dun say so early hor... U c already then say...
4       ham  Nah I don't think he goes to usf, he lives aro...
...     ...                                                ...
5567   spam  This is the 2nd time we have tried 2 contact u...
5568    ham              Will Ì_ b going to esplanade fr home?
5569    ham  Pity, * was in mood for that. So...any other s...
5570    ham  The guy did some bitching but I acted like i'd...
5571    ham                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [42]:
from src.utils import data_cleaning
from src.constant.constants import *
df['clean_data'] = df[FEATURES_NAME].apply(data_cleaning)

In [102]:
df

Target                                       Text_Message
0          0  Go until jurong point, crazy.. Available only ...
1          0                      Ok lar... Joking wif u oni...
2          1  Free entry in 2 a wkly comp to win FA Cup fina...
3          0  U dun say so early hor... U c already then say...
4          0  Nah I don't think he goes to usf, he lives aro...
...      ...                                                ...
5567       1  This is the 2nd time we have tried 2 contact u...
5568       0              Will Ì_ b going to esplanade fr home?
5569       0  Pity, * was in mood for that. So...any other s...
5570       0  The guy did some bitching but I acted like i'd...
5571       0                         Rofl. Its true to its name

[5572 rows x 2 columns]

In [103]:
df[FEATURES_NAME].isna().sum()

0

In [104]:
model_path = r"F:\End_To_End_project\Ham_Spam_Classifier(ETE)\artifact\01_31_2024_06_29_03\model_trainer\model\lstm.h5"
path = r"F:\End_To_End_project\Ham_Spam_Classifier(ETE)\artifact\01_31_2024_03_28_10\data_transformation\preprocess_file\preprocess.pkl"

In [106]:
spam 

array(["Free entry in 2 a wkly comp to win FA Cup final tkts 21st May 2005. Text FA to 87121 to receive entry question(std txt rate)T&C's apply 08452810075over18's",
       "FreeMsg Hey there darling it's been 3 week's now and no word back! I'd like some fun you up for it still? Tb ok! XxX std chgs to send, å£1.50 to rcv",
       'WINNER!! As a valued network customer you have been selected to receivea å£900 prize reward! To claim call 09061701461. Claim code KL341. Valid 12 hours only.',
       'Had your mobile 11 months or more? U R entitled to Update to the latest colour mobiles with camera for Free! Call The Mobile Update Co FREE on 08002986030',
       'SIX chances to win CASH! From 100 to 20,000 pounds txt> CSH11 and send to 87575. Cost 150p/day, 6days, 16+ TsandCs apply Reply HL 4 info',
       'URGENT! You have won a 1 week FREE membership in our å£100,000 Prize Jackpot! Txt the word: CLAIM to No: 81010 T&C www.dbuk.net LCCLTD POBOX 4403LDNW1A7RW18',
       'XXXMobileMovieClub:

In [107]:
from src.utils import load_tokenizer
from tensorflow.keras.models import load_model
preprocess = load_tokenizer(path)

loaded_model = load_model(model_path)

Tokenizer loaded from F:\End_To_End_project\Ham_Spam_Classifier(ETE)\artifact\01_31_2024_03_28_10\data_transformation\preprocess_file\preprocess.pkl


In [108]:
new_data = ["Hello, this is a legitimate message.", "Congratulations! You've won a prize. Claim it now!"]

In [110]:
sequences = tokenizer.texts_to_sequences(spam)

padded_sequences = pad_sequences(sequences, maxlen=60)

In [111]:
padded_sequences

array([[   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,   15,  830,    2,  933,  765, 5020,  111, 1676, 1042,
         310, 1677, 2015,  207, 2016,   24, 1676, 5020, 1678, 5020,  276,
         812,   31,  304,  844, 4132],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,  667,   79, 1895,  103, 1087, 2866,  548,  172,   41,   17,
         324,   26, 1733,  631,   39, 1679,   13,  313,  812, 3769, 5020,
          25,  260,  173, 5020, 2580],
       [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
           0,    0,    0,    0,   

In [112]:
predictions = loaded_model.predict(padded_sequences)

1/1 [==============================] - 1s 531ms/step


In [113]:
predictions

array([[0.0120088 ],
       [0.01178741],
       [0.0117259 ],
       [0.01234225],
       [0.01206208],
       [0.01201766],
       [0.01176629],
       [0.01164065],
       [0.01141816],
       [0.01120537]], dtype=float32)

In [114]:
import numpy as np
binary_predictions = np.round(predictions).astype(int)
binary_predictions

# for i, text in enumerate(new_data):
#     print(f"Text: {text}\nPredicted Label: {'Spam' if binary_predictions[i] == 1 else 'Ham'}\n")

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [2]:
import os
os.chdir('..')
%pwd

'f:\\End_To_End_project\\Ham_Spam_Classifier(ETE)'

In [3]:
path = r"artifact\01_31_2024_07_05_48\model_trainer\model"
y = r"artifact\01_31_2024_07_05_48\data_transformation\feature_target_data\label.npy"
x = r"artifact\01_31_2024_07_05_48\data_transformation\feature_target_data\Text_pad_sequences.npy"

models = os.listdir(path)
models

['combined.h5', 'lstm.h5', 'rnn.h5']

In [9]:
from src.components.data_ingetion import DataIngestion
from src.utils import load_and_split_data

In [11]:
X_train, X_test, y_train, y_test = load_and_split_data(x,y)

NameError: name 'TEST_SET_SIZE' is not defined

In [ ]:
model = load_model(model_path)

            logging.info('Making predictions on test data...')
            y_pred = model.predict(X_test)
            y_pred = (y_pred > 0.5).astype(int)

            logging.info('Calculating accuracy...')
            accuracy = accuracy_score(y_test, y_pred)

            logging.info(f'Model Accuracy: {accuracy}')